name: GitHub Actions Demo
run-name: ğŸ¤– ChrisBot
on:
  pull_request:
#    TODO add back later
#    paths:
#      - "**/*.md"
#      - "**/*.mdx"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo ".md or .mdx file has been modified."

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Fetch full git history
        run: git fetch --prune --unshallow
      #     - name: Fetch latest `main` branch
      #     run: git fetch origin main --depth=1

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci
        working-directory: ./tools/ai-docs-assistant

      - name: Run Node.js script
        run: npm run start
        working-directory: ./tools/ai-docs-assistant
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#jobs:
#  Explore-GitHub-Actions:
#    runs-on: ubuntu-latest
#    steps:
#      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event!"
#      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#      - name: Check out repository code
#        uses: actions/checkout@v4
#      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
#      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
#      - name: List files in the repository
#        run: |
#          ls ${{ github.workspace }}
#      - run: echo "ğŸ This job's status is ${{ job.status }}."
#
